/**
 * Labels that can never be a tenant subdomain: they are infrastructure hosts or
 * would be confusing/phishable (`login.`, `billing.`). A reserved label under the
 * root domain is served as the apex host rather than as a tenant.
 */
export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
    "www",
    "api",
    "admin",
    "app",
    "apps",
    "auth",
    "login",
    "signin",
    "signup",
    "register",
    "account",
    "accounts",
    "billing",
    "dashboard",
    "console",
    "static",
    "assets",
    "cdn",
    "media",
    "files",
    "mail",
    "email",
    "smtp",
    "ftp",
    "docs",
    "blog",
    "help",
    "support",
    "status",
    "staging",
    "dev",
    "test",
    "demo",
    "root",
    "system",
    "platform",
    "internal",
    "security",
    "webhooks",
    "ns1",
    "ns2",
]);
